### PR TITLE
Default to latest Sourcegraph release (3.36.2)

### PR DESCRIPTION
**Pull request by caugustus-sourcegraph**
No significant changes for this release, version bump only

### CODE REVIEW

**Review by kevinwojo — APPROVED** [review]
confirming bump

**Review by michaellzc — APPROVED** [review]

**Comment by michaellzc** [comment]
just curious, is this a manual change or it was done by batch change?

**Comment by caugustus-sourcegraph** [comment]
@michaellzc - I ran a local script that pulls the images from the release branches in the deploy repos 😅  I haven't checked it in because it's a temporary hack and not for anyone to use.

This project is still in beta and hasn't yet been incorporated into the batch changes functionality. The tricky part is that the batch changes ultimately rely on https://github.com/sourcegraph/update-docker-tags, which only works against full image references. The values.yaml doesn't expose the full image directly so we need to make some code changes to support the new use case. That work isn't yet planned but it will be required soon.

**Review by filiphaftek — APPROVED** [review]
👍

**Pull request merged**
