### PR TITLE
Release/5.3

### PR DESCRIPTION
**Pull request by Chickensoupwithrice**
### Checklist

- [x] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [ ] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
- [ ] Update [Kubernetes update doc](https://docs.sourcegraph.com/admin/updates/kubernetes)

### Test plan
Release Image

### CODE REVIEW

**Comment by Chickensoupwithrice** [comment]
Looks like releases haven't been merged into main since 5.3.0? Do we want to be doing this?

**Review by DaedalusG — APPROVED** [review]

**Review by BolajiOlajide — APPROVED** [review]
@jdpleiness Can you have a look at this? I know we normally don't cherry-pick the release branch changes to `main` here, but this is a better improvement for folks who are viewing our helm chart and don't know how the release branches work.

However, I wonder if this would break any changes to how the helm charts are uploaded. I know we once had an issue you helped fix but can't remember why that happened anymore, so just flagging in case there's potential for any breaking changes with this PR.

**Review by jdpleiness — APPROVED** [review]
@BolajiOlajide yeah this makes sense. The issue we face last time was that we had to patch a release version but the charts were already uploaded and our GH action doesn't overwrite an old chart.

In this case, the charts will get published to `https://helm.sourcegraph.com/insiders/5.3.x` rather than `https://helm.sourcegraph.com/release/x` which I don't see any issues with.

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide yeah this makes sense. The issue we face last time was that we had to patch a release version but the charts were already uploaded and our GH action doesn't overwrite an old chart.
> 
> In this case, the charts will get published to `https://helm.sourcegraph.com/insiders/5.3.x` rather than `https://helm.sourcegraph.com/release/x` which I don't see any issues with.

Thank you for double checking.

**Comment by Chickensoupwithrice** [comment]
Since double checking that we don't need to merge this, I'm closing this one

**Pull request closed without merging**
