### PR TITLE
release: cherrypick 5.6.185 release

### PR DESCRIPTION
**Pull request by jdpleiness**
### Checklist

- [x] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [x] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
- [x] Update [Kubernetes update doc](https://docs.sourcegraph.com/admin/updates/kubernetes)

### Test plan

Tested locally

### CODE REVIEW

**Review by Chickensoupwithrice — APPROVED** [review]

**Comment by Chickensoupwithrice** [comment]
I thought we don't merge these?

**Comment by jdpleiness** [comment]
> I thought we don't merge these?

We haven't for some time, but this has actually been on the backlog of items we need to fix. I've gone ahead and done them manually for this time around though as some of our deployments were _very_ out of date in `main`.

**Review by michaellzc — APPROVED** [review]
i thought we're pinning to `insiders` on main?

**Comment by jdpleiness** [comment]
> i thought we're pinning to `insiders` on main?

Longterm that might be the goal but there are some additional concerns around that and our customer experience as well. Until that is worked out, this is just a one-off stopgap PR to get it up to date with the convention we had been using.

**Pull request merged**
