### PR TITLE
Give ctags a writable temp dir

### PR DESCRIPTION
**Pull request by chrismwendt**
Because the `symbols` container's processes run as user 100 (`sourcegraph`):

https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/b6d554e3f594b9c43951f84520f174fae29114ab/charts/sourcegraph/values.yaml#L997

ctags doesn't have write permission to `/tmp`.

### Checklist

- [ ] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)

### Test plan

Tested in https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4594

### CODE REVIEW

**Review by michaellzc — APPROVED** [review]
lgtm

but we should ask delivery to take another look

**Review by caugustus-sourcegraph — APPROVED** [review]

**Comment by kevinwojo** [comment]
@chrismwendt do you know about how much data is to be written to this location? What will disk utilization respond to?

**Comment by chrismwendt** [comment]
@kevinwojo ctags appears to write a few MB to `TMPDIR` then immediately deletes the data, so to be safe I'd say it needs 1GB of space. It reads/writes a lot, so an SSD is best.

**Comment by chrismwendt** [comment]
Reviewers: I added a volume to ensure that the `/mnt/tmp` directory always exists, otherwise ctags fails.

**Review by caugustus-sourcegraph — APPROVED** [review]
Approving again, for the extra volume mount approach

**Pull request merged**
