### PR TITLE
Set deploy_type env var to track helm chart usage

### PR DESCRIPTION
**Pull request by caugustus-sourcegraph**
Enable tracking of helm chart usage by using the deploy_type env var.

### Checklist

- [x] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)

### Test plan

Compared diffs before and after - new env var is set. Frontend will crash unless the changes from https://github.com/sourcegraph/sourcegraph/pull/32407 are present.

### CODE REVIEW

**Comment by caugustus-sourcegraph** [comment]
@michaellzc - this is another one for the "can't merge until the release" bucket. I added the `release-blocker` label to this and the postgres PR so we can at least track it until we have a better process.

**Review by michaellzc — APPROVED** [review]
lgtm

**Comment by michaellzc** [comment]
Since now we have one more PR that can only be merged right before the release.

Should we add a release label `release-3.39` on them so it will be easier to track? Just as a reminder for our self to merge them before the minor release

**Comment by camdencheek** [comment]
@caugustus-sourcegraph @michaellzc Same question as [here](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/57#issuecomment-1071149353): this will just be merged before the release tomorrow, right?

**Pull request merged**
